#!/usr/bin/env bash
CIRCUIT=anonymous_stand_in
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BASE_DIR=${SCRIPT_DIR}
OUT_DIR=${BASE_DIR}/out


# use the input.json generated by generateInput.sh here

cd ${OUT_DIR}/${CIRCUIT}_js

node generate_witness.js ${CIRCUIT}.wasm ../input.json witness.wtns

npx snarkjs groth16 prove ${CIRCUIT}_0001.zkey witness.wtns proof.json public.json

npx snarkjs groth16 verify verification_key.json public.json proof.json

npx snarkjs generatecall | tee call_remix.txt
cat call_remix.txt | perl -lape 's/\"(.*?)"/uint($1)/g' > call_solidity.txt
